#!/bin/bash

set -eufo pipefail

if ! command -v curl &> /dev/null; then
    echo "Unable to find the 'curl' command. Aborting."
    exit 1
fi

if ! command -v brew &> /dev/null; then
    url="https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh"
    if bash -c "$(curl -fsSL $url)"; then
        cat << EOF
Install of homebrew was successful.
- To continue, refresh your shell and check "chezmoi status".
EOF
    else
        echo "Install of homebrew was unsuccessful."
    fi
fi
