#!/bin/bash

# NOTE: This script is ran strategically when it is helpful at the beginning of
# a "chezmoi apply" to call "chezmoi init". This is done in order to not require
# the user to have to run multiple init calls, when it is determined to be
# needed. Yes, it is probably hacky.

# HACK: Calling the init command here while apply command is already running
# will cause a "timeout obtaining persistent state lock" error. We aren't really
# needing to modify persistent state here, but rather we simply want to call
# init so that it can (re-)build our config file. To work around this we are
# pointing persistent state to a temporary file for the init call (if called).

set -eufo pipefail

temp_file="$(mktemp)"
trap 'rm -f "$temp_file"' EXIT INT TERM HUP
chezmoi init --persistent-state="$temp_file"
