# Setup ls-related abbreviations
abbr -a -- l ls
abbr -a -- la 'ls -A'
abbr -a -- la! 'ls -a'
abbr -a -- ll 'ls -lh'
abbr -a -- lla 'ls -lhA'
abbr -a -- lla! 'ls -lha'

# Setup misc shell abbreviations
abbr -a -- - 'cd -'
abbr -a -- cp 'cp -iRv'
abbr -a -- cp! 'cp -fRv'
abbr -a -- md 'mkdir -v'
abbr -a -- md! 'mkdir -pv'
abbr -a -- mv 'mv -iv'
abbr -a -- mv! 'mv -fv'
abbr -a -- rd 'rmdir -v'
abbr -a -- rd! 'rmdir -pv'
abbr -a -- rm 'rm -irv'
abbr -a -- rm! 'rm -frv'

# Setup chezmoi abbreviations
abbr -a -- cdcz 'cd (chezmoi source-path)'
abbr -a -- cz chezmoi
abbr -a -- cza 'chezmoi add'
abbr -a -- czap 'chezmoi apply'
abbr -a -- czap! 'chezmoi apply --init'
abbr -a -- czat 'chezmoi chattr'
abbr -a -- czc 'chezmoi cat'
abbr -a -- czcd 'chezmoi cd'
abbr -a -- czd 'chezmoi diff'
abbr -a -- czda 'chezmoi data'
abbr -a -- czdr 'chezmoi doctor'
abbr -a -- cze 'chezmoi edit'
abbr -a -- cze! 'chezmoi edit --apply'
abbr -a -- czg 'chezmoi git'
abbr -a -- czga! 'chezmoi git add -- --all'
abbr -a -- czgau 'chezmoi git add -- -u'
abbr -a -- czgc 'chezmoi git commit -- -m'
abbr -a -- czgc! 'chezmoi git commit -- --amend'
abbr -a -- czgd 'chezmoi git diff'
abbr -a -- czgds 'chezmoi git diff --staged'
abbr -a -- czgf! 'chezmoi git fetch -- --all'
abbr -a -- czgg 'chezmoi git grep'
abbr -a -- czgl 'chezmoi git log'
abbr -a -- czgl! 'chezmoi git log -- --show-signature'
abbr -a -- czgp 'chezmoi git push'
abbr -a -- czgp! 'chezmoi git push -- --force'
abbr -a -- czgre! 'chezmoi git reset -- --hard origin/main'
abbr -a -- czgs 'chezmoi git status'
abbr -a -- czi 'chezmoi init'
abbr -a -- czi! 'chezmoi init --apply'
abbr -a -- czig 'chezmoi ignored'
abbr -a -- czm 'chezmoi managed'
abbr -a -- czsr 'chezmoi state delete-bucket --bucket=entryState'
abbr -a -- czsr! 'chezmoi state reset'
abbr -a -- czs 'chezmoi status'
abbr -a -- czu 'chezmoi update --apply=false'
abbr -a -- czu! 'chezmoi update'
abbr -a -- czu!! 'chezmoi update --init'
abbr -a -- czum 'chezmoi unmanaged'
abbr -a -- czx 'chezmoi execute-template \'{{'
abbr -a -- czxf 'chezmoi execute-template -f'

# Setup git abbreviations
abbr -a -- g git
abbr -a -- ga 'git add'
abbr -a -- ga! 'git add --all'
abbr -a -- gau 'git add -u'
abbr -a -- gc 'git commit -m'
abbr -a -- gc! 'git commit --amend'
abbr -a -- gd 'git diff'
abbr -a -- gds 'git diff --staged'
abbr -a -- gf 'git fetch'
abbr -a -- gf! 'git fetch --all'
abbr -a -- gg 'git grep'
abbr -a -- gl 'git log'
abbr -a -- gl! 'git log --show-signature'
abbr -a -- gp 'git push'
abbr -a -- gp! 'git push --force'
abbr -a -- gr 'git rm -r'
abbr -a -- gr! 'git rm -rf'
abbr -a -- gre! 'git reset --hard origin/main'
abbr -a -- gs 'git status'
